.TH "folder-thumbnailer" "1" "April 23, 2019" "" "folder-thumbnailer"
.SH "NAME"
folder-thumbnailer - program to generate folder cover.
.br

.SH "SYNOPSIS"
\fBfolder-thumbnailer \fR<thumbnail-size> <folder-name> <output> <folder-path>
.br

.SH "DESCRIPTION"
Create thumbnail from folder.
.br

\fBfolder-thumbnailer\fR is for creating folder thumbnail.
.br

It uses folder.jpg/.folder.jpg/folder.png/cover.jpg to create thumbnail.
.br
